branches:
  only:
    - master

language: python

python:
  - "3.6"

git:
  depth: false

install:
  - pip install -r requirements.txt

script:

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $OAUTH_TOKEN
  keep-history: true
  verbose: true
  target-branch: master
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = "cron"
